# Generated by Django 6.1 on 2026-08-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parent',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic_covered', models.CharField(max_length=200)),
                ('skill_rating', models.IntegerField(choices=[(1, '1 - Needs improvement'), (2, '2 - Developing'), (3, '3 - Satisfactory'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('tutor_comments', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='students.parent')),
            ],
        ),
    ]
