# Generated by Django 6.1 on 2026-08-31 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_parent_outstanding_balance_parent_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='relationship_to_student',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_in_advance', models.BooleanField(default=False, verbose_name='I understand all payments are made in advance')),
                ('pays_on_time', models.BooleanField(default=False, verbose_name='I understand missed payments may pause sessions')),
                ('understands_no_refund', models.BooleanField(default=False, verbose_name='I understand the no-refund policy')),
                ('gives_24h_notice', models.BooleanField(default=False, verbose_name="I will give 24 hours' notice for absences")),
                ('child_on_time', models.BooleanField(default=False, verbose_name='I will ensure my child arrives and is collected on time')),
                ('confirm_terms', models.BooleanField(default=False, verbose_name='I confirm I have read and agree to all terms')),
                ('confirms_official_contact', models.BooleanField(default=False, verbose_name='I confirm I will only use the official STC contact number')),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(help_text='Health, allergies, conditions, learning/behavioural needs, medications. Enter N/A if none.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='students.student')),
            ],
        ),
    ]
