# Generated by Django 6.1 on 2026-08-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_parent_relationship_to_student_student_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolmentagreement',
            name='additional_questions',
            field=models.TextField(blank=True, default='', verbose_name='Questions, concerns, or special requests for STC (optional)'),
        ),
    ]
