# Generated by Django 6.1 on 2026-08-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrolmentagreement_additional_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='enrolment_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
