# Generated by Django 6.1 on 2026-08-31 13:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_parent_enrolment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('applies_to', models.CharField(choices=[('centre', 'Centre'), ('home', 'Home tuition')], default='centre', help_text='Which delivery type this plan applies to.', max_length=20)),
                ('sessions_per_payment', models.PositiveIntegerField(default=8, help_text='Sessions covered by one payment. Centre block = 8, home = 1.')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('175.00'), help_text='Auto price for one payment (e.g. £175 for an 8-session block).', max_digits=8)),
                ('assessment_fee', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='One-off assessment fee charged on first payment (0 if none).', max_digits=8)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override used instead of base_price (e.g. a discount or custom deal).', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_note',
            field=models.CharField(blank=True, default='', help_text="Optional note explaining a custom price / discount (e.g. 'sibling discount').", max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('block', 'Session block'), ('session', 'Home session'), ('assessment', 'Assessment fee')], default='block', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional start time.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='delivery_type',
            field=models.CharField(choices=[('centre', 'Centre'), ('home', 'Home tuition')], default='centre', help_text='Centre tuition or home tuition — determines pricing.', max_length=20),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('assessment_date', models.DateField()),
                ('topics', models.CharField(blank=True, default='', max_length=200)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tutor_notes', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student')),
            ],
            options={
                'ordering': ['assessment_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The payment plan this invoice was generated from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='students.paymentplan'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_plan',
            field=models.ForeignKey(blank=True, help_text='The payment plan this student is billed under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.paymentplan'),
        ),
    ]
