# Generated by Django 6.1 on 2026-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_paymentplan_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sessions_used_in_block',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
