# Generated by Django 6.1 on 2026-08-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_sessions_used_in_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('is_head_office', models.BooleanField(default=False, help_text='Head office (franchisor) may view every centre; franchisees see only their own.')),
                ('session_slots', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre this plan belongs to; null = plan is shared by all centres.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='students.centre'),
        ),
        migrations.AddField(
            model_name='student',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='The centre this student attends. Determines venue, pricing and which staff can see them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.centre'),
        ),
        migrations.AddField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='The centre this staff account is tied to (null for head-office/global staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='students.centre'),
        ),
    ]
