# Generated by Django 6.1 on 2026-09-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_centre_paymentplan_centre_student_centre_user_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='topics',
        ),
        migrations.AddField(
            model_name='assessment',
            name='overall_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_group', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.assessment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
