"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--rvu2!_7m$t92%vcp!q0!5*_n6yoa=v^0@jzho_aart!=!hm(k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


# ---------------------------------------------------------------------------
# Production security flags
# ---------------------------------------------------------------------------
# These only take effect when DEBUG is off, so local development over plain
# http://127.0.0.1:8000 keeps working while production enforces HTTPS and
# protects session/auth cookies. Default to False locally; set the env vars
# (e.g. SECURE_SSL_REDIRECT=true) when deploying.
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "false").lower() == "true"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "false").lower() == "true"
# Modern replacement for the old (removed-in-Django-6) SECURE_BROWSER_XSS_FILTER:
# even where the X-XSS-Protection header is ignored, send a strict referrer
# policy, forbid the browser guessing MIME types, and block the site being
# framed (defending against clickjacking).
SECURE_BROWSER_XSS_FILTER = os.getenv("SECURE_BROWSER_XSS_FILTER", "false").lower() == "true"
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "true").lower() != "false"
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "true").lower() != "false"
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "true").lower() != "false"
    SECURE_BROWSER_XSS_FILTER = os.getenv("SECURE_BROWSER_XSS_FILTER", "true").lower() != "false"
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Your App 
    'core',
    'students',
    # Third-party 
    'tailwind'
]
# Custom User Model
AUTH_USER_MODEL = "students.User"
AUTHENTICATION_BACKENDS = [
    "students.auth_backends.EmailCaseInsensitiveBackend",
]
# Tailwind theme settings
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH ='npm' # path for npm
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.getenv("USE_SQLITE", "false").lower() == "true":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("POSTGRES_DB"),
            'USER': os.getenv("POSTGRES_USER"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
            'HOST': os.getenv("POSTGRES_HOST"),
            'PORT': os.getenv("POSTGRES_PORT")
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [    BASE_DIR / 'static',
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Real (SMTP) mail is used once EMAIL_HOST_USER / EMAIL_HOST_PASSWORD are set in
# .env. Until then we fall back to the console backend so local dev still works
# and every outgoing message prints to the runserver terminal.
EMAIL_CONSOLE = not bool(
    os.getenv("EMAIL_HOST_USER") and os.getenv("EMAIL_HOST_PASSWORD")
)

if EMAIL_CONSOLE:
    _smtp_options = {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    }
else:
    # 1&1 IONOS (smtp.ionos.co.uk) — new-style MAILERS config.
    # OPTIONS maps straight onto the SMTP backend constructor, so the keys are
    # lowercase: host, port, username, password, use_tls, timeout.
    _smtp_options = {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': os.getenv("EMAIL_HOST", "smtp.ionos.co.uk"),
            'port': int(os.getenv("EMAIL_PORT", "587")),
            'username': os.getenv("EMAIL_HOST_USER"),
            'password': os.getenv("EMAIL_HOST_PASSWORD"),
            'use_tls': os.getenv("EMAIL_USE_TLS", "true").lower() == "true",
            'timeout': int(os.getenv("EMAIL_TIMEOUT", "30")),
        },
    }

MAILERS = {'default': _smtp_options}

# Admins are emailed on every new enrolment via mail_admins()
ADMINS = [("STC Admin", os.getenv("ADMIN_EMAIL", "admin@sloughtuitioncentre.co.uk"))]
DEFAULT_FROM_EMAIL = (
    os.getenv("EMAIL_HOST_USER", "") if not EMAIL_CONSOLE else os.getenv(
        "DEFAULT_FROM_EMAIL", "Slough Tuition Centre <no-reply@sloughtuitioncentre.co.uk>"
    )
)

